// Code generated by goyacc block.y. DO NOT EDIT.

//line block.y:2
package parser

import __yyfmt__ "fmt"

//line block.y:2

import "sbl.systems/go/synwork/synwork/ast"
import "log"

//import "strconv"

func print(s string) {
	log.Println(s)
}

//line block.y:14
type yySymType struct {
	yys    int
	raw    *Token
	node   ast.Node
	array  []interface{}
	strar  []string
	strval string
}

const IDENT = 57346
const LBRACE = 57347
const RBRACE = 57348
const STRING = 57349
const ASSIGN = 57350
const INTEGER = 57351
const FLOAT = 57352
const MINUS = 57353
const PLUS = 57354
const DOLLAR = 57355
const DOT = 57356
const TRUE = 57357
const FALSE = 57358

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"LBRACE",
	"RBRACE",
	"STRING",
	"ASSIGN",
	"INTEGER",
	"FLOAT",
	"MINUS",
	"PLUS",
	"DOLLAR",
	"DOT",
	"TRUE",
	"FALSE",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 41

var yyAct = [...]int{

	11, 7, 5, 18, 36, 22, 25, 24, 23, 28,
	7, 26, 27, 14, 13, 15, 15, 17, 32, 33,
	30, 31, 7, 12, 6, 9, 12, 29, 3, 35,
	4, 20, 34, 21, 19, 16, 10, 37, 8, 2,
	1,
}
var yyPact = [...]int{

	-1000, 24, -1000, -1000, 17, -1000, -1000, -1000, 19, -1000,
	-1000, 5, -1000, -1000, -4, 23, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 11, 9, -1000, -1000, -1000, 22, -1000,
	-1000, -1000, -1000, -1000, -10, 4, 22, 4,
}
var yyPgo = [...]int{

	0, 40, 39, 38, 36, 2, 35, 34, 33, 32,
	31, 30, 0,
}
var yyR1 = [...]int{

	0, 1, 1, 2, 5, 3, 3, 4, 4, 6,
	6, 6, 6, 6, 7, 7, 7, 7, 7, 7,
	8, 9, 9, 12, 12, 10, 10, 11, 11,
}
var yyR2 = [...]int{

	0, 0, 2, 3, 3, 2, 0, 2, 3, 1,
	1, 1, 1, 1, 1, 2, 2, 1, 2, 2,
	2, 3, 1, 3, 1, 1, 1, 2, 0,
}
var yyChk = [...]int{

	-1000, -1, -2, 4, -11, -5, 7, 5, -3, 6,
	-4, -12, 4, -5, 8, 11, -6, -5, 7, -7,
	-10, -8, 9, 12, 11, 10, 15, 16, 13, 4,
	9, 10, 9, 10, -9, -12, 14, -12,
}
var yyDef = [...]int{

	1, -2, 2, 28, 0, 3, 27, 6, 0, 4,
	5, 0, 24, 7, 0, 0, 8, 9, 10, 11,
	12, 13, 14, 0, 0, 17, 25, 26, 0, 23,
	15, 18, 16, 19, 20, 22, 0, 21,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line block.y:53
		{
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line block.y:56
		{
			yylex.(*Tokenizer).consumeBlock(yyDollar[2].node.(*ast.BlockNode))
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line block.y:61
		{
			bcn := yyDollar[3].node.(*ast.ComplexValue)
			yyVAL.node = &ast.BlockNode{Begin: yyDollar[1].raw.Position, Type: yyDollar[1].raw.RawString, Identifiers: yyDollar[2].strar, Content: &bcn.BlockContentNode}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line block.y:68
		{
			yyVAL.node = &ast.ComplexValue{*(yyDollar[2].node.(*ast.BlockContentNode))}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line block.y:72
		{
			bcn := yyDollar[1].node.(*ast.BlockContentNode)
			switch n := yyDollar[2].node.(type) {
			case *ast.AssignmentNode:
				bcn.Assignments = append(bcn.Assignments, n)
			case *ast.BlockNode:
				bcn.Blocks = append(bcn.Blocks, n)
			}
			yyVAL.node = bcn
		}
	case 6:
		yyDollar = yyS[yypt-0 : yypt+1]
//line block.y:83
		{
			yyVAL.node = &ast.BlockContentNode{Assignments: []*ast.AssignmentNode{}, Blocks: []*ast.BlockNode{}}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line block.y:87
		{
			bcn := yyDollar[2].node.(*ast.ComplexValue)
			yyVAL.node = &ast.BlockNode{Begin: "", Type: yyDollar[1].strval, Content: &bcn.BlockContentNode}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line block.y:93
		{
			yyVAL.node = &ast.AssignmentNode{Begin: yyDollar[2].raw.Position, Identifier: yyDollar[1].strval, Value: yyDollar[3].node.(ast.ValueNode)}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:97
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:100
		{
			yyVAL.node = &ast.StringValue{Begin: yyDollar[1].raw.Position, Value: yyDollar[1].raw.RawString}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:103
		{
			yyVAL.node = yyDollar[1].node
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:106
		{
			yyVAL.node = yyDollar[1].node
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:109
		{
			yyVAL.node = yyDollar[1].node
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:113
		{
			yyVAL.node = &ast.IntValue{Begin: yyDollar[1].raw.Position, Value: convertIntValue(1, yyDollar[1].raw.RawString)}
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line block.y:116
		{
			yyVAL.node = &ast.IntValue{Begin: yyDollar[1].raw.Position, Value: convertIntValue(1, yyDollar[2].raw.RawString)}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line block.y:119
		{
			yyVAL.node = &ast.IntValue{Begin: yyDollar[1].raw.Position, Value: convertIntValue(-1, yyDollar[2].raw.RawString)}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:122
		{
			yyVAL.node = &ast.FloatValue{Begin: yyDollar[1].raw.Position, Value: convertFloatValue(1, yyDollar[1].raw.RawString)}
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line block.y:125
		{
			yyVAL.node = &ast.FloatValue{Begin: yyDollar[1].raw.Position, Value: convertFloatValue(1, yyDollar[2].raw.RawString)}
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line block.y:128
		{
			yyVAL.node = &ast.FloatValue{Begin: yyDollar[1].raw.Position, Value: convertFloatValue(-1, yyDollar[2].raw.RawString)}
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line block.y:132
		{
			yyVAL.node = &ast.ReferenceValue{Begin: yyDollar[1].raw.Position, RefParts: yyDollar[2].strar}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line block.y:136
		{
			yyVAL.strar = append(yyDollar[1].strar, yyDollar[3].strval)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:139
		{
			yyVAL.strar = []string{yyDollar[1].strval}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line block.y:142
		{
			yyVAL.strval = yyDollar[1].strval + "-" + yyDollar[3].raw.RawString
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:144
		{
			yyVAL.strval = yyDollar[1].raw.RawString
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:148
		{
			yyVAL.node = &ast.BoolValue{Begin: yyDollar[1].raw.Position, Value: true}
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line block.y:151
		{
			yyVAL.node = &ast.BoolValue{Begin: yyDollar[1].raw.Position, Value: false}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line block.y:156
		{
			yyVAL.strar = append(yyDollar[1].strar, yyDollar[2].raw.RawString)
		}
	case 28:
		yyDollar = yyS[yypt-0 : yypt+1]
//line block.y:158
		{
			yyVAL.strar = []string{}
		}
	}
	goto yystack /* stack new state and value */
}
